{{ if not .Values.qbittorrent.vpn.secret.existing }}
apiVersion: v1
data:
    {{ .Values.qbittorrent.vpn.secret.privateKeySecretKey }}: {{ .Values.qbittorrent.vpn.secret.privateKey }}
    {{ .Values.qbittorrent.vpn.secret.addressesSecretKey }}: {{ .Values.qbittorrent.vpn.secret.addresses }}
kind: Secret
metadata:
  name: {{ .Values.qbittorrent.vpn.secret.name }}
  namespace: {{ .Release.Namespace }}
{{ end }}