apiVersion: v1
data:
{{ if not .Values.qbittorrent.vpn.secret.existing }}
    {{ .Values.qbittorrent.vpn.secret.privateKeySecretKey }}: {{ .Values.qbittorrent.vpn.secret.privateKey }}
    {{ .Values.qbittorrent.vpn.secret.addressesSecretKey }}: {{ .Values.qbittorrent.vpn.secret.addresses }}
{{ end }}
{{ if not .Values.discord.secret.existing }}
    {{ .Values.discord.secret.tokenSecretKey }}: {{ .Values.discord.secret.token }}
{{ end }}
kind: Secret
metadata:
  name: arr-secret
  namespace: {{ .Release.Namespace }}