apiVersion: apps/v1
kind: Deployment
metadata:
  name: arr-auth
  namespace: media
  labels:
    app: arr-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arr-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: arr-auth
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: thomseddon/traefik-forward-auth:2
        name: arr-auth
        ports:
        - containerPort: 4181
          protocol: TCP
        env:
        - name: LOG_LEVEL
          value: info
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: arr-auth-secret
              key: cookie-secret
        - name: INSECURE_COOKIE
          value: "true"
        - name: DEFAULT_PROVIDER
          value: oidc
        - name: PROVIDERS_OIDC_ISSUER_URL
          value: https://auth.ryzen.me/realms/public
        - name: PROVIDERS_OIDC_CLIENT_ID
          value: arr
        - name: PROVIDERS_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: arr-auth-secret
              key: client-secret