apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: bazarr-config
spec:
  storageClassName: {{ .Values.arr.config.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.arr.config.size }}