apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbit-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: qbit-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi