apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qbit
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: qbit
  ports:
    - name: qbittorrent
      port: {{ .Values.qbittorrent.config.web_port }}
      targetPort: {{ .Values.qbittorrent.config.web_port }}